memcached:
  image: memcached
  ports:
    - "6379"

pythonserver:
  build: .
  command: python server.py
  volumes:
    - .:/code
  ports:
    - "8000"
  links:
    - memcached

nginx:
  build: ./nginx
  volumes:
    - ./nginx/static:/app/static/
    - ./nginx/media:/app/media/
  links:
    - pythonserver
  ports:
    - "80:80"
